const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

// السماح بقراءة البيانات بصيغة JSON من الطلبات القادمة من الموقع
app.use(express.json());

// لخدمة ملفات الموقع الثابتة (index.html, style.css, script.js)
app.use(express.static(__dirname));

// مسار خاص بالذكاء الاصطناعي لتوليد الأكواد والرد على المستخدمين
app.post('/api/ai', async (req, res) => {
    try {
        const { prompt, lang } = req.body;

        if (!prompt) {
            return res.status(400).json({ error: 'الرجاء إدخال الطلب أو السؤال!' });
        }

        // هنا يمكنك ربط سيرفرك بـ API حقيقي (مثل Google Gemini API أو OpenAI)
        // حالياً تم عمل محاكاة ذكية متقدمة تفهم لغات البرمجة وترد عليك بشكل احترافي:
        let aiGeneratedCode = `// تم التوليد بواسطة مساعد Crystal AI الخارق\n// اللغة: ${lang ? lang.toUpperCase() : 'GENERAL'}\n// الطلب: ${prompt}\n\n`;

        if (lang === 'js') {
            aiGeneratedCode += `console.log("Crystal AI: تنفيذ الكود بنجاح");\nfunction executeTask() {\n    return "تم معالجة طلب JavaScript بنجاح وترميز آمن.";\n}\nexecuteTask();`;
        } else if (lang === 'lua') {
            aiGeneratedCode += `-- FiveM Lua Script Generated by Crystal AI\nRegisterNetEvent('crystal:server:init')\nAddEventHandler('crystal:server:init', function()\n    print(\"^2[Crystal Secure]^7: النظام يعمل بكفاءة عالية.\")\nend)`;
        } else if (lang === 'py') {
            aiGeneratedCode += `import sys\n\ndef crystal_main():\n    print("Crystal AI Python Engine: Active")\n\nif __name__ == "__main__":\n    crystal_main()`;
        } else {
            aiGeneratedCode += `/* Crystal AI Output */\nbody {\n    background: #07090e;\n    color: #00f2fe;\n}`;
        }

        res.json({ success: true, result: aiGeneratedCode });

    } catch (error) {
        res.status(500).json({ error: 'حدث خطأ في خادم الذكاء الاصطناعي: ' + error.message });
    }
});

app.listen(PORT, () => {
    console.log(`💎 منصة كريستل تعمل الآن بكامل طاقتها على الرابط: http://localhost:${PORT}`);
});
